{% set version = "1.3.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-lexicon
  version: {{ version|replace("-", "_") }}

source:
  fn: lexicon_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/lexicon_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lexicon/lexicon_{{ version }}.tar.gz
  sha256: fdddbb6a6343ca5d6b57838069f96f38a8b943e277c140e5077796cd662855a1

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-data.table
    - r-syuzhet >=1.0.1
  run:
    - r-base
    - r-data.table
    - r-syuzhet >=1.0.1

test:
  commands:
    - $R -e "library('lexicon')"           # [not win]
    - "\"%R%\" -e \"library('lexicon')\""  # [win]

about:
  home: https://github.com/trinker/lexicon
  license: GPL-3
  summary: A collection of lexical hash tables, dictionaries, and word lists.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - CurtLH
