appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Cde24ih5ixXVWDKC2l6oK40wDhwJlvQ0O6QGTg0kN4zeD8yoQyUhVaPYnsN56yUcqJHaYF1dTMbUxImjhjHGxHnt6yTIKrLn0QAzzL8t4FeDs25gHZ/3x74FlsBB+5nm+QFBPXxd4HJZHEUWN30T20o+uvaTIHQmQIPtOrAAjnxG1gOccPO49bN2yBPS39T6YUxzMdKkFvpkTtYArlfeE+6QLKCGiXGZam5VDaeqC2eEOg5ytf+mUygOKCeJVyzR2NOe/DkqGUOOFBbWYcubFwCR7GpWDWbAnKMwxXhqd+7FnYPa6nmj6BUxD+ulkhIL3maMZsoq2EF9ZpE/Jz6JA+Snx9n9uPD6Tf9rjZtGOHiHllKRLWD+LZQUwjSUUSPUsYduaH/30nerTW9LjxoSQmpvPH6s4l+BkrTy5Mf05H9fLH35XduS8SyAhLjRd0DQ2gyIe/7R6q9GZovvT3MXgIwfVm4RQ3jaAzFv+HX8CmrUJLAGscL6/bvtfAVTF/ahsH8vMR7fYAeLKI0nC8obeXzSHNC3IWZNs7yX7RjG44q5THOIv8LTRtzsbKRDsr/vbdwQ0L6CdWP18EQbFhgqJl/IWw4EH2djcAaeZDa03mViCCIcr/jmjrGsuB1Eon9wm7Snnjc2tWnJai2rn3VF1ywFF2cg/PQ+MBUoa6y6fCk=}
