travis:
  secure:
    BINSTAR_TOKEN: Oleuah2CBq+hPNZmC+lcEY73tXRtrVkzTOqdub6OmomXRIBbNWI2jWKXc/yNIk6i6xDyz1+K5VMDMEYkdEbRxzfaA3kwIMH85Ru++Y4zH8i3oblHEeM6CTa2poq41KlpIJRN/kNNIscfuTBmfBWodPux9j8AjaVmwF+vDJWcWWjEhaMVgFe1auhYAJdxV+fXM5whoi33Of1YFvkfpQZCuTQ1jMha8dnST+P6AtjZAzsAylWYbJDRtPFifcQsPh0Sts7GecIeNLxgfr5KiZC1bqO6DEROrpfXLvuM9gdNi9Cy4sTUoONrUB8seQNB2ODMaoBY5CUlVZspb+yKR7SAa0F2fgLkSgVGf/5gx3y6I7gb5euztSFrz0kGuR9t1YCgjg7jaeRxMPm5qXj5ozdAXlvq1U2UkasTYsUUaXXEs24K8oRzN5jmqCnBDHrmDGCRzxyDHlEqsasoiadYSNoB88uFNTgySGjwA9hHc/3pL7/wWnbK6i0+xMOQCJPgq9nJG0yMViBX+Uds8TZB3Pn7CCJ0heQ9RkaNCZeuJ1Dp1UVTullRAVN4VlOidWMybpxYMgrWtX/ij2plc1h1i1rdHdRIsZPanzJQK+eMFKyq4KVfytei8ZWqTkOpB3PaimfyMSWHNrvHiVQ2soOTE7uXpZbj4fm2Z4diSyLj9HCyGL0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
